python vamshi.py "select A from table1"
python vamshi.py "select * from table2"
python vamshi.py "select B,C from table1"
python vamshi.py "select distinct(A) from table1"
python vamshi.py "select max(C) from table1"
python vamshi.py "select min(B) from table1"
python vamshi.py "select avg(A) from table1"
python vamshi.py "select sum(A) from table1"
python vamshi.py "select * from table1 where A > 100"
python vamshi.py  "select * from table1,table2 where A > 100 and B < 500"
python vamshi.py "select distinct A,B from table1"